# Welcome
In this repository, I have included a .CSV file for the 98th Awards and the 97th Awards. Each one contains a transcript of that year's Best Picture nominations.

You will notice that these .CSV files do not contain speaker names. This is to avoid copyright infringement and publishing a reproduceable script. The analysis is here, but the .CSV files containing the names of the speakers are hidden.

In [53]:
import pandas as pd
import re

awards_98th = pd.read_csv('awards_98th.csv')
awards_97th = pd.read_csv('awards_97th.csv')

# This code puts each of this year's films (98th awards) into their own dataframes.
# This way, if I want to analyze just one film, I can.

the_secret_agent = awards_98th[awards_98th['film'] == 'THE SECRET AGENT']
hamnet = awards_98th[awards_98th['film'] == 'HAMNET']
sentimental_value = awards_98th[awards_98th['film'] == 'SENTIMENTAL VALUE']
sinners = awards_98th[awards_98th['film'] == 'SINNERS']
bugonia = awards_98th[awards_98th['film'] == 'BUGONIA']
train_dreams = awards_98th[awards_98th['film'] == 'TRAIN DREAMS']
marty_supreme = awards_98th[awards_98th['film'] == 'MARTY SUPREME']
f_one = awards_98th[awards_98th['film'] == 'F-ONE']
frankenstein = awards_98th[awards_98th['film'] == 'FRANKENSTEIN']
one_battle_after_another = awards_98th[awards_98th['film'] == 'ONE BATTLE AFTER ANOTHER']

# Here I do the same for the movies from the 97th Awards.

wicked = awards_97th[awards_97th['film'] == 'WICKED']
im_still_here = awards_97th[awards_97th['film'] == "I'M STILL HERE"]
the_brutalist = awards_97th[awards_97th['film'] == 'THE BRUTALIST']
the_substance = awards_97th[awards_97th['film'] == 'THE SUBSTANCE']
dune_part_two = awards_97th[awards_97th['film'] == 'DUNE: PART TWO']
emilia_perez = awards_97th[awards_97th['film'] == 'EMILIA PEREZ']
nickel_boys = awards_97th[awards_97th['film'] == 'NICKEL BOYS']
conclave = awards_97th[awards_97th['film'] == 'CONCLAVE']
anora = awards_97th[awards_97th['film'] == 'ANORA']
a_complete_unknown = awards_97th[awards_97th['film'] == 'A COMPLETE UNKNOWN']

# Data Analysis for Pie Charts (Viz 1)
## 'Women speak about a quarter of the words in this year's Best Picture nominations. Last year, they spoke about a third of them'
Here, I calculate the percentage of words spoken across genders per award year overall. This shows across all 10 movies this year (98th Awards), women spoke about a quarter of the words, and last year (97th Awards) they spoke about a third of them.

In [54]:
# Quantifiable question: How many words does each gender speak across all Best Picture nominations in the 98th Awards?
# Gives me a pivot table with the answers.

In [55]:
# Quantifiable question: How many words does each gender speak across all Best Picture nominations in the 98th Awards?
# Gives me a pivot table with the answers.

awards_98th.groupby('speaker_gender')['word_count_corrected'].sum()

speaker_gender
FEMALE       27287
MALE         75890
MIXED          503
NONBINARY       25
UNKNOWN          3
Name: word_count_corrected, dtype: int64

After this, I simply plug these numbers into Flourish and it creates the pie chart. But to fact check that women speak about 25% in Python, I use the following code.

In [56]:
# Quantifiable question: How many words are spoken in total across all Best Picture nominations in the 98th Awards?
# Gives me an integer as the answer.

awards_98th['word_count_corrected'].sum()

np.int64(103708)

In [57]:
# What's the percentage of words spoken by women?
# 26.3% -- about a quarter of the words.

27287 / 103708

0.2631137424306707

Below, I do the exact same thing for the 97th Awards.

In [58]:
awards_97th.groupby('speaker_gender')['word_count_corrected'].sum()

speaker_gender
FEMALE    34191
MALE      57423
MIXED      1061
Name: word_count_corrected, dtype: int64

In [59]:
awards_97th['word_count_corrected'].sum()

np.int64(92675)

In [60]:
34191 / 92675

0.36893444834097655

# Data Analysis for Column Charts - Gender by Individual Film (Viz 2 & 3)
## "Men do most of the talking, but women take the lead in 'Sentimental Value' and 'Hamnet'"
## "Last year, women spoke the majority of words in three films by over at least 60%"
Below, I create a series of pivot tables showing the number of words spoken by each gender per film. Then, I save them as .CSV files -- one for each award year.

In [61]:
# Here I create a pivot table for the 98th Awards with films as rows and genders as columns.

gender_by_film_98 = awards_98th.pivot_table(
    values='word_count_corrected',
    index='film',
    columns='speaker_gender',
    aggfunc='sum',
    fill_value=0
)

# Here I add a column for total words.
gender_by_film_98['TOTAL'] = gender_by_film_98.sum(axis=1)

# Here I add a totals row for each gender.
totals_row = gender_by_film_98.sum(axis=0)
totals_row.name = 'TOTAL'
gender_by_film_98 = pd.concat([gender_by_film_98, totals_row.to_frame().T])

# And here I save it as a .CSV file.
gender_by_film_98.to_csv('gender_by_film_98.csv')

In [62]:
gender_by_film_98

speaker_gender            FEMALE   MALE  MIXED  NONBINARY  UNKNOWN   TOTAL
BUGONIA                     4006   5068      0          0        0    9074
F-ONE                       1813  11767     11          0        0   13591
FRANKENSTEIN                 831   7458      0          0        0    8289
HAMNET                      3607   3450      0          0        0    7057
MARTY SUPREME               3380  15772      4          0        0   19156
ONE BATTLE AFTER ANOTHER    3020   9401      0         25        0   12446
SENTIMENTAL VALUE           3947   2946      3          0        0    6896
SINNERS                     2621   8649    461          0        3   11734
THE SECRET AGENT            2890   6591     13          0        0    9494
TRAIN DREAMS                1172   4788     11          0        0    5971
TOTAL                      27287  75890    503         25        3  103708

In [63]:
# This is the same as the above, except for the 97th Awards.

gender_by_film_97 = awards_97th.pivot_table(
    values='word_count_corrected',
    index='film',
    columns='speaker_gender',
    aggfunc='sum',
    fill_value=0
)

gender_by_film_97['TOTAL'] = gender_by_film_97.sum(axis=1)

totals_row = gender_by_film_97.sum(axis=0)
totals_row.name = 'TOTAL'
gender_by_film_97 = pd.concat([gender_by_film_97, totals_row.to_frame().T])

gender_by_film_97.to_csv('gender_by_film_97.csv')

In [64]:
gender_by_film_97

speaker_gender      FEMALE   MALE  MIXED  TOTAL
A COMPLETE UNKNOWN    1774  10259     84  12117
ANORA                 5861   8381     17  14259
CONCLAVE               221   7585      0   7806
DUNE: PART TWO        2693   4040     80   6813
EMILIA PEREZ          5801   1336    307   7444
I'M STILL HERE        4447   2698      2   7147
NICKEL BOYS           1256   6282      1   7539
THE BRUTALIST         3267  11428      9  14704
THE SUBSTANCE         1338   2393      0   3731
WICKED                7533   3021    561  11115
TOTAL                34191  57423   1061  92675

# Data Analysis for Bar Charts - Words per Lead Character + Their Gender (Viz 4 & 5)
## "How much do lead characters speak in their films?"
## And, "Last year featured more lead women than men -- and they generally spoke more than them too"
Below, I create pivot tables showing the total number of words spoken by each lead character (and their film and gender) for each award year, and save them as .CSV files. Afterwords, I input the data into Flourish to create the bar charts.

In [65]:
# Here, I create a pivot table that filter out lead characters, their films, their genders, and the sum of their word counts for the 98th Awards.
lead_character_wc_98th = awards_98th[awards_98th['speaker_role'] == 'LEAD'].groupby(['film', 'speaker']).agg({
    'word_count_corrected': 'sum',
    'speaker_gender': 'first'
}).reset_index()

# Here, I add a column that shows the total word count for each film, subtracted by the lead character's word count.
# In Flourish, this allows me to show the lead character's word count in the context of the rest of the film's dialogue.
film_total_wc = awards_98th.groupby('film')['word_count_corrected'].sum()
lead_character_wc_98th['other_characters_wc'] = lead_character_wc_98th['film'].map(film_total_wc) - lead_character_wc_98th['word_count_corrected']

lead_character_wc_98th.to_csv('lead_character_wc_98th.csv', index=False)

lead_character_wc_98th

,film,speaker,word_count_corrected,speaker_gender,other_characters_wc
0,BUGONIA,MICHELLE,3516,FEMALE,5558
1,BUGONIA,TEDDY,3709,MALE,5365
2,F-ONE,SONNY,2485,MALE,11106
3,FRANKENSTEIN,VICTOR,3377,MALE,4912
4,HAMNET,AGNES,2230,FEMALE,4827
5,MARTY SUPREME,MARTY,8884,MALE,10272
6,ONE BATTLE AFTER ANOTHER,BOB,3453,MALE,8993
7,SENTIMENTAL VALUE,NORA,1302,FEMALE,5594
8,SINNERS,SMOKE,1869,MALE,9865
9,SINNERS,STACK,1671,MALE,10063
10,THE SECRET AGENT,MARCELO,1785,MALE,7709
11,TRAIN DREAMS,GRAINIER,1395,MALE,4576

In [66]:
# And here is the same as above for the 97th Awards.
lead_character_wc_97th = awards_97th[awards_97th['speaker_role'] == 'LEAD'].groupby(['film', 'speaker']).agg({
    'word_count_corrected': 'sum',
    'speaker_gender': 'first'
}).reset_index()

film_total_wc = awards_97th.groupby('film')['word_count_corrected'].sum()
lead_character_wc_97th['other_characters_wc'] = lead_character_wc_97th['film'].map(film_total_wc) - lead_character_wc_97th['word_count_corrected']

lead_character_wc_97th.to_csv('lead_character_wc_97th.csv', index=False)

lead_character_wc_97th

,film,speaker,word_count_corrected,speaker_gender,other_characters_wc
0,A COMPLETE UNKNOWN,BOB,4383,MALE,7734
1,ANORA,ANI,4468,FEMALE,9791
2,CONCLAVE,LAWRENCE,3056,MALE,4750
3,DUNE: PART TWO,PAUL,1440,MALE,5373
4,EMILIA PEREZ,EMILIA,2048,FEMALE,5396
5,EMILIA PEREZ,RITA,2294,FEMALE,5150
6,I'M STILL HERE,EUNICE,2255,FEMALE,4892
7,NICKEL BOYS,ELWOOD,1108,MALE,6431
8,NICKEL BOYS,TURNER,1678,MALE,5861
9,THE BRUTALIST,LASZLO,3575,MALE,11129
10,THE SUBSTANCE,ELISABETH,599,FEMALE,3132
11,THE SUBSTANCE,SUE,614,FEMALE,3117
12,WICKED,ELPHABA,2806,FEMALE,8309

# Data Analysis for Heatmap (Viz 6)
## "Who do characters talk about more: themselves or others?"

I wanted to see if I could measure characters' interest in themselves vs. others, and compare that across genders. So, I analyzed the number of select "I" words and "you" words for each gender per movie, and was able to determine a ratio that shows the degree to which characters speak more or less self-referentially.

This segment code was created with assistance from Claude AI, and was manually fact-checked with a random sample of movies.

The code creates a function that counts the number of words characters use that refer to themselves ("I" words) and the number of words used that refer to the people they speak to ("you" words). Then, the code compares them as a "I-to-You" for each gender's usage per film.

The analysis that comes from this code has some limitations. It excludes first-person plural pronouns like "we" and "us". Also, if characters refer to someone else by their name (and not by a "you"), it isn't counted, which means some words (names) characters say referring to others aren't counted. It also doesn't count third person pronouns, like "he," "she" or "they."

While this code might be useful for getting an idea of characters' interest in themselves vs. others, it of course has its limitations and should not be used as a definitive evaluation.

In [67]:
# This defines the main function
def analyze_words(source, label=None):  # 'source' is the data, 'label' is an optional title like a film name
    """
    Count I-to-YOU pronoun ratio by gender.

    Parameters:
        source  : pd.DataFrame or str path to a CSV file
        label   : optional label for the output header (e.g. film name)
    """
    # ^ this is a docstring: a plain-English description of the function, not executed as code

    # This defines the words I'm looking for: I words and you words.
    # Each list is created twice — once with straight apostrophes and once with curly apostrophes —
    # so the code catches contractions regardless of how they were typed in the source data.
    curly = chr(8217)  # stores the curly apostrophe character ' (as opposed to the straight one ') so contractions like "i'm" can be matched in both styles

    you_words = {'you', 'your', 'yours', 'yourself', "you're", "you've", "you'll", "you'd", "y'all", 'you-', 'your-', 'yours-', 'yourself-', "you're-", "you've-", "you'll-", "you'd-", "y'all-", 'yourselves', 'yourselves-', 'thou', 'thou-', 'thy', 'thy-', 'thee', 'thee-', 'thine', 'thine-'}  # defines a set of all "you"-related words to look for
    you_words.update([w.replace("'", curly) for w in you_words])  # adds curly-apostrophe versions of each contraction to the same set, so both styles are covered

    i_words = {'i', "i'm", "i've", "i'll", "i'd", 'my', 'mine', 'me', 'myself', 'i-', "i'm-", "i've-", "i'll-", "i'd-", 'my-', 'mine-', 'me-', 'myself-'}  # defines a set of all "I"-related words to look for
    i_words.update([w.replace("'", curly) for w in i_words])  # adds curly-apostrophe versions of each contraction, same as above

    # This loads the data from the source.
    if isinstance(source, str):  # checks whether 'source' is a file path (a string) rather than a ready-made table of data
        df = pd.read_csv(source)  # if so, reads the CSV file into a DataFrame (a table) called 'df'
        label = label or source  # if no label was provided, uses the file path as the label
    else:
        df = source  # if 'source' is already a DataFrame, just use it directly

    # This checks that the data has the two columns this code needs to work: speaker_gender and dialogue.
    # If not, it stops immediately and explains what's missing.
    required_cols = {'speaker_gender', 'dialogue'}
    if not required_cols.issubset(df.columns):  # checks whether both required columns exist in the data
        raise ValueError(f"Data must contain columns: {required_cols}. Found: {set(df.columns)}")  # if not, stops the code and prints a helpful error message

    # This finds the genders in the data.
    # Looks at the data and automatically detects however many genders are present,
    # so the code works no matter what the data contains.
    genders = sorted(df['speaker_gender'].dropna().unique().tolist())  # finds all unique gender values in the data, removes blanks, and sorts them alphabetically into a list

    # This is a smaller function used inside the main one.
    # It takes a set of dialogue lines and counts the "I"-words and "you"-words within them.
    def count_pronouns(dialogues):
        all_text = ' '.join(dialogues.astype(str))  # joins all dialogue lines into one long string with spaces between them
        words = re.findall(r"\b[A-Z]+(?:['\u2019][A-Z]+)*\b", all_text)  # extracts every word (including contractions) from the text using a pattern; \u2019 is the curly apostrophe, \b marks word boundaries - does not extract words where "I" is part of the word
        words = [w.lower() for w in words]  # converts every word to lowercase so "I" and "i" are treated the same

        you_count = 0  # sets a counter for "you"-words, starting at zero
        i_count = 0  # sets a counter for "I"-words, starting at zero

        for word in words:  # This loops through every word one at a time
            if word in you_words:  # checks if the word is in the "you" set
                you_count += 1  # if so, adds 1 to the "you" counter
            # If the word matched you, you should not also count it as an "I" word, 
            # so I would continue to the next.
            # Or you can keep the below and raise an error. That would be something I'd want to 
            # know b/c it's unexpected and could be an indication of miscounts
            if word in i_words:  # checks if the word is in the "I" set (separate check, not else/if)
                i_count += 1  # if so, adds 1 to the "I" counter

        return you_count, i_count  # sends both counts back to wherever the function was called from

    # This counts each word per gender.
    # Splits the data by gender, runs the word-counting function on each group,
    # and stores the results ready to be printed.
    you_counts = {}  # creates an empty dictionary to store "you"-word counts per gender
    i_counts = {}  # creates an empty dictionary to store "I"-word counts per gender
    for gender in genders:  # loops through each gender found in the data
        dialogues = df[df['speaker_gender'] == gender]['dialogue']  # filters the data to just that gender's rows and grabs the dialogue column
        you_counts[gender], i_counts[gender] = count_pronouns(dialogues)  # runs count_pronouns on those dialogues and stores the two results

    # This prints the table header.
    # Prints the film name (or label) and the column headings at the top of the output table.
    header = f" {label} " if label else ""  # wraps the label in spaces if one was provided, otherwise leaves it blank
    print(f"\n{'='*10}{header}{'='*10}")  # prints a header line like "========== Hamnet =========="

    header_row = f"{'':20}"  # starts the column header row with a blank 20-character space for the label column
    for gender in genders:  # loops through each gender
        header_row += f"  {gender:>8}"  # adds the gender name right-aligned in an 8-character field
    print(header_row)  # prints the completed column header row
    print("-" * (20 + len(genders) * 10))  # prints a dividing line sized to match the table width

    # This prints the raw number of "I"-words and "you"-words each gender uses.
    i_row = f"{'  I words':<20}"  # starts the "I words" row with its label
    for gender in genders:  # loops through each gender
        i_row += f"  {i_counts[gender]:>8}"  # adds that gender's "I"-word count
    print(i_row)  # prints the completed "I words" row

    you_row = f"{'  YOU words':<20}"  # starts the "YOU words" row with its label
    for gender in genders:  # loops through each gender
        you_row += f"  {you_counts[gender]:>8}"  # adds that gender's "you"-word count
    print(you_row)  # prints the completed "YOU words" row

    print("-" * (20 + len(genders) * 10))  # prints a final dividing line before the ratio

    # This prints the I-to-YOU ratio.
    # It divides each gender's "I"-word count by their "you"-word count to produce a ratio.
    # A ratio above 1 means they use more "I"-words than "you"-words, and vice versa.
    ratio_row = f"{'  I-to-YOU ratio':<20}"  # starts the ratio row with its label
    for gender in genders:  # loops through each gender
        i = i_counts[gender]  # retrieves that gender's "I"-word count
        y = you_counts[gender]  # retrieves that gender's "you"-word count
        ratio = (i / y) if y > 0 else 0  # divides I by YOU to get the ratio; uses 0 if there are no "you"-words to avoid a division-by-zero error
        ratio_row += f"  {ratio:>7.2f}x"  # adds the ratio formatted to 2 decimal places with an "x" suffix
    print(ratio_row)  # prints the completed ratio row

In [68]:
# Here I apply the analyze_words function to the 98th Award films, which allows me to analyze their Self-to-Other ratios by gender.

analyze_words(hamnet, label='HAMNET')
analyze_words(sentimental_value, label='SENTIMENTAL VALUE')
analyze_words(sinners, label='SINNERS')
analyze_words(bugonia, label='BUGONIA')
analyze_words(train_dreams, label='TRAIN DREAMS')
analyze_words(marty_supreme, label='MARTY SUPREME')
analyze_words(f_one, label='F-ONE')
analyze_words(frankenstein, label='FRANKENSTEIN')
analyze_words(one_battle_after_another, label='ONE BATTLE AFTER ANOTHER')
analyze_words(the_secret_agent, label='THE SECRET AGENT')

========== HAMNET ==========
                        FEMALE      MALE
----------------------------------------
  I words                  202       218
  YOU words                220       191
----------------------------------------
  I-to-YOU ratio         0.92x     1.14x

========== SENTIMENTAL VALUE ==========
                        FEMALE      MALE     MIXED
--------------------------------------------------
  I words                  284       152         0
  YOU words                191       177         0
--------------------------------------------------
  I-to-YOU ratio         1.49x     0.86x     0.00x

========== SINNERS ==========
                        FEMALE      MALE     MIXED   UNKNOWN
------------------------------------------------------------
  I words                  151       501        33         0
  YOU words                160       494         2         0
------------------------------------------------------------
  I-to-YOU ratio         0.94x     1.01x    16.50x     0.00x

========== BUGONIA ==========
                        FEMALE      MALE
----------------------------------------
  I words                  255       283
  YOU words                200       307
----------------------------------------
  I-to-YOU ratio         1.27x     0.92x

========== TRAIN DREAMS ==========
                        FEMALE      MALE     MIXED
--------------------------------------------------
  I words                   53       197         0
  YOU words                 56       162         1
--------------------------------------------------
  I-to-YOU ratio         0.95x     1.22x     0.00x

========== MARTY SUPREME ==========
                        FEMALE      MALE     MIXED
--------------------------------------------------
  I words                  287      1204         0
  YOU words                224       983         0
--------------------------------------------------
  I-to-YOU ratio         1.28x     1.22x     0.00x

========== F-ONE ==========
                        FEMALE      MALE     MIXED
--------------------------------------------------
  I words                   70       409         0
  YOU words                 96       406         0
--------------------------------------------------
  I-to-YOU ratio         0.73x     1.01x     0.00x

========== FRANKENSTEIN ==========
                        FEMALE      MALE
----------------------------------------
  I words                   41       505
  YOU words                 36       360
----------------------------------------
  I-to-YOU ratio         1.14x     1.40x

========== ONE BATTLE AFTER ANOTHER ==========
                        FEMALE      MALE  NONBINARY
--------------------------------------------------
  I words                  198       489         4
  YOU words                208       584         0
--------------------------------------------------
  I-to-YOU ratio         0.95x     0.84x     0.00x

========== THE SECRET AGENT ==========
                        FEMALE      MALE     MIXED
--------------------------------------------------
  I words                  180       426         0
  YOU words                120       328         0
--------------------------------------------------
  I-to-YOU ratio         1.50x     1.30x     0.00x

With this information, I plug the results into the Flourish spreadsheet, which visualizes the ratios in a heatmap. I have downloaded this spreadsheet as a .CSV file and included it in this repository.

# Data Analysis for Article Discussion: Does each lead character speak more words than any other character?
Below are a series of groupbys that allow me to check if each film's lead character speaks the most words out of any other character in their film for the 98th Award Year. I found that leads speak more than others in everything except 'Sentimental Value' and 'Train Dreams.'

In 'F1,' it shows "COMMENTATOR" as speaking more words than Sonny, the main character. "COMMENTATOR" is, for certain, more than one character -- though it's not clear how many. I believe there are two unnamed commentators, but since we rarely see them in the film and only hear their dialogue, it's hard to differentiate one from the other. Therefore, I record them all as COMMENTATOR, making it seem like they are one character when they are not. With that in mind, it is most likely that Sonny still says the most words.

This data isn't visualized in Flourish but is discussed in the article.

In [69]:
bugonia.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
TEDDY              3709
MICHELLE           3516
CASEY               618
DON                 524
NEWSCASTER          129
PODCAST MAN         109
SANDY               105
PODCAST WOMAN       104
ANDROMEDAN           54
DETECTIVE            47
COREY                40
DETECTIVE 2          35
TINA                 25
YOUNG DETECTIVE      18
GUARD                14
CHRIS                13
CARLOS                6
NURSE                 5
TONY                  2
COWORKER              1
Name: word_count_corrected, dtype: int64

In [70]:
sinners.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
SMOKE            1869
STACK            1671
SAMMIE           1220
REMMICK          1169
SLIM             1030
ANNIE             899
MARY              724
CORNBREAD         422
CROWD             414
PEARLINE          344
GRACE             332
MAN               330
BO                252
JOAN              200
PASTOR            188
BERT              186
HOGWOOD           119
TERRY             100
CHOCTAW MAN        57
KIDS               47
BEATRICE           29
GIRL               28
MA                 26
MEN                22
THERISE            13
WOMAN              11
CHOCTAW MAN 2      11
LISA                8
RUTHIE              4
SIBLING             3
IRISH SINGER        3
SISTER              2
SARAH               1
Name: word_count_corrected, dtype: int64

In [71]:
one_battle_after_another.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
BOB            3453
MAN            1493
LOCKJAW        1123
PERFIDIA        944
SERGIO          820
WOMAN           813
VIRGIL          555
WILLA           550
DANVERS         455
SANDY           338
TIM             250
BILL            168
RADIO MAN       165
DEANDRA         141
TOEJAM          131
ROCHELLE        120
GIRL             91
MINNIE           83
BOY              68
BEEGEE           67
JUNGLEPUSSY      66
TALLEYRAND       65
ROY              62
AVANTI           57
REINA            53
VOX              47
SOMERVILLE       45
ALICE            41
BLUTO            37
RADIO WOMAN      34
MARISELA         26
BOBO             25
SKINNER          22
PRINCIPAL        16
MAE              11
MEN               8
DERRICK           3
Name: word_count_corrected, dtype: int64

In [72]:
sentimental_value.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
GUSTAV                2011
NORA                  1302
AGNES                  895
RACHEL                 828
NARRATOR               631
INTERVIEWER            182
JAKOB                  150
MICHAEL                115
WOMAN                   94
PETER                   87
EVEN                    84
ERIK                    84
SAM                     56
ARCHIVE CLERK           56
DIRECTOR                52
OLD WOMAN               32
PATIENT                 32
STAGE MANAGER           32
NICKY                   24
OLAV                    19
INGRID                  17
THERESE                 13
NURSE                   13
VETERAN ACTOR           13
SISSEL                  12
PRODUCER                 9
ACTOR                    9
WAITRESS                 8
HOST                     6
MAN                      5
TRAIN WOMAN              5
ASSISTANT DIRECTOR       4
KARIN                    4
TECHNICIAN               3
GROUP                    3
SEAMSTER                 2
OLIVIA                   2
ANNA                     1
SOLDIER                  1
Name: word_count_corrected, dtype: int64

In [73]:
train_dreams.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
NARRATOR        1533
GRAINIER        1395
MAN              991
ARN              591
GLADYS           573
CLAIRE           552
FRANK            131
BILLY             86
RADIO MAN         42
KATIE             33
HANK              14
WOMAN             14
GROUP             11
PHOTOGRAPHER       5
Name: word_count_corrected, dtype: int64

In [74]:
frankenstein.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
VICTOR        3377
CREATURE      1005
HARLANDER      918
ELIZABETH      691
WILLIAM        522
MAN            441
GRANDPA        411
CAPTAIN        340
FATHER         257
CREWMAN        138
WOMAN           69
ANNA-MARIA      54
CREWMEN         27
MOTHER          17
MEN             12
SERVANT          8
UDSEN            2
Name: word_count_corrected, dtype: int64

In [75]:
f_one.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
COMMENTATOR        3740
SONNY              2485
JOSHUA             1298
KATE               1205
RUBEN              1152
MAN                1111
PETER               486
KASPAR              408
REPORTER            305
HUGH                295
WOMAN               184
DON                 144
MOM                 133
BERNADETTE          120
RADIO MAN            88
CHIP                 86
OLD COMMENTATOR      73
JODIE                59
RACER                41
LISBETH              40
ZAK                  24
FEMALE REPORTER      21
TOTO                 18
RADIO WOMAN          17
WAITRESS             17
MOLLY                16
GROUP                11
CALE                  6
DODGE                 5
FRED                  2
GIRL                  1
Name: word_count_corrected, dtype: int64

In [76]:
the_secret_agent.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
MARCELO         1785
SEBASTIANA       829
EUCLIDES         651
FERNANDO         596
HENRIQUE         540
FLAVIA           448
ALEXANDRE        383
ELZA             353
ANISIO           342
AUGUSTO          327
FRENTISTA        252
TEREZA           226
VALDEMAR         207
MAN              206
CLAUDIA          191
ELISANGELA       181
PEDRO            181
FATIMA           142
BOBBI            138
ARLINDO          137
RADIO MAN        131
WOMAN            126
VILMAR           117
DANIELA          110
SERGIO           102
HANS              89
INES              88
OFFICER           88
HAROLDO           74
DORES             68
LUANDA            48
CLOVIS            37
ANTONIO           34
CARMEN            27
RECEPTIONIST      26
SUSAN             23
SALVATORE         21
SANJAY            20
GERALDO           18
SCIENTIST         18
OFFICER 2         14
GROUP             13
DESIDERIO         13
IRINEU            12
MARCAO            11
LENIRA            10
LAWYER             9
WRITER             7
DEBORA             5
WAITER             5
JANITOR            4
ROSA               3
JOANA              3
SEVERINO           2
BOY                2
OLIVEIRA           1
Name: word_count_corrected, dtype: int64

In [77]:
hamnet.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
AGNES          2230
HUSBAND        1808
MARY            500
HAMLET          421
HAMNET          314
SUSANNA         256
BARTHOLOMEW     233
JUDITH          209
ACTOR 1         179
JOAN            171
JOHN            130
CLAUDIUS         91
ROWAN            69
MIDWIFE          60
WOMAN            47
ELIZA            46
BERNARDO         44
HORATIO          41
LAERTES          40
GERTRUDE         33
BOYS             25
MAN              20
FRANCISCO        17
MARCELLUS        17
BOY              14
ACTOR 2          13
CATERINA          9
WOMAN 2           8
OSRIC             5
MAN 2             5
MAID              2
Name: word_count_corrected, dtype: int64

In [78]:
marty_supreme.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
MARTY       8884
RACHEL      1640
KAY         1005
ROCKWELL     962
WALLY        729
            ...
PLUMBER        3
ENDO           3
BRIAN          2
SOLDIER        1
GIRL           1
Name: word_count_corrected, Length: 72, dtype: int64

In [79]:
conclave.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
LAWRENCE     3056
BELLINI      1108
MAN           839
BENITEZ       635
RAY           514
TREMBLAY      474
ADEYEMI       305
TEDESCO       280
AGNES         217
SABBADIN      212
WILLI          56
WOZNIAK        49
NAKITANDA      29
MEN            28
WOMAN           4
Name: word_count_corrected, dtype: int64

In [80]:
a_complete_unknown.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
BOB               4383
PETE              1986
JOAN               790
SYLVIE             728
ALBERT             528
                  ...
NEWSCASTER           4
DANNY                3
REPORTER MALE        3
MALE ASSISTANT       3
DRUMMER              3
Name: word_count_corrected, Length: 65, dtype: int64

In [81]:
im_still_here.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
EUNICE             2255
RUBENS              674
ELIANA              464
MARCELO             394
VEROCA              390
NALU                289
BABY                281
BABIU               274
ZEZE                202
FELIX               194
INTERROGATOR        189
MAN                 130
TV MAN              124
MARTHA              122
TV WOMAN            115
OFFICER             114
LINO                 90
GIRL                 72
SOLDIER              58
SOLDIERS             58
PHOTOGRAPHER         57
DALAL                57
CARLA                52
DAD                  46
DALVA                44
PHONE MAN            43
WOMAN                40
BEATRIZ              34
GASPA                34
RITOR                32
SCHNEIDER            28
CHICO                23
JUCA                 18
PIMPAO               18
JOURNALIST           16
REPORTER 2           16
BOY                  15
DETAINEE             14
REPORTER             11
CRIS                 10
MARLON                9
RADIO MAN             7
FRIEND                7
COUSIN                7
RAUL                  6
GERALDO               5
BOYS                  2
GROUP                 2
COLLEAGUE             2
RAQUEL                1
CUSTOMS OFFICER       1
TELLER                1
Name: word_count_corrected, dtype: int64

In [82]:
anora.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
ANI                4468
TOROS              3205
IVAN               2110
GARNIK             1130
IGOR                589
GALINA              300
CRYSTAL             262
TOM                 202
ATTORNEY            197
DIAMOND             164
MAN                 151
WOMAN               146
TOW MAN             144
CLERK               128
JUDGE               117
DAWN                113
JIMMY               106
ALEKS                86
MALE REPORTER        76
OFFICIANT            72
LULU                 52
FEMALE REPORTER      47
DAY GUARD            41
NIKOLAI              37
BUTLER               36
HOSTESS              35
WOMAN 1              31
RICKY                30
OFFICER              26
DJ                   25
MAN 5                18
BILLY                18
ALL                  17
MAN 1                13
WOMAN 2              13
WOMAN 3              10
MAN 4                 7
JENNY                 7
WOMAN 4               6
PRIEST                6
KLARA                 5
MAN 3                 3
MAN 2                 3
DEALER                3
DAISY                 2
MEN                   1
igor                  1
Name: word_count_corrected, dtype: int64

In [83]:
emilia_perez.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
RITA         2294
EMILIA       2048
JESSI         918
MAN           599
GROUP         307
WOMAN         239
WASSERMAN     217
EPIFANIA      216
GUSTAVO       210
BOY 2         162
WOMEN          71
BOY            49
DOCTOR         42
TV MAN         41
PILOT MAN      16
TV WOMAN       13
COLLEAGUE       2
Name: word_count_corrected, dtype: int64

In [84]:
wicked.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
GLINDA               2994
ELPHABA              2806
WIZARD                836
MADAME MORRIBLE       834
FIYERO                634
DR. DILLAMOND         558
THROPP                231
NESSAROSE             227
MISS CODDLE           203
BOQ                   171
STUDENTS              147
OZIANS                133
PFANNEE               128
HISTORY PROFESSOR      98
NARRATOR               87
ENSEMBLE               87
SHIZ PRESIDENT         79
RESIDENTS              79
SHENSHEN               75
PINK ACTRESS           69
WOMAN                  56
MAGENTA ACTRESS        56
DULCIBEAR              55
CHOIR                  44
GUARD                  39
BOY                    27
GIRL                   26
MAN                    26
PIEBALD DEER           25
TRAVELERS              21
GUARDS                 20
WOLF DOCTOR            19
FELDSPUR               18
CONDUCTOR              17
ANNOUNCER              16
POPSICLE               15
SNOW LEOPARD           13
KIDS                   13
RAT                    13
ALL                    13
BOY 2                   9
LEOPARD                 9
GUARD 2                 9
MRS THROPP              8
MAID                    8
MAN 2                   7
ANIMAL                  7
STUDENT                 6
GIRL 2                  6
WOMAN 4                 6
MRS. THROPP             5
MOMSIE                  5
WOMAN 2                 5
OTHER ANIMALS           4
WOMAN 3                 4
MAN 3                   3
BIRD PROFESSOR          3
DANCERS                 2
TAMARIN MONKEY          1
Name: word_count_corrected, dtype: int64

In [85]:
the_brutalist.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
LASZLO             3575
HARRISON           2890
ERZSEBET           2086
HARRY              1013
ATTILA              943
MAN                 544
LESLIE              500
ZSOFIA              432
REPORTER            394
GORDON              314
MAGGIE              310
ORAZIO              227
RADIO MAN           209
AUDREY              195
JIM                 163
OFFICER 1           139
MAYOR               125
MICHAEL             115
ALBERT               57
MRS HOFFMAN          56
SEX WORKER           49
MAN 3                46
MAN 2                42
RECEPTIONIST         36
WOMAN                36
ZUNZ                 32
BINYAMIN             29
MESSENGER            23
NURSE                22
MEN                  20
BOY                  17
ELIZABETH            13
SEX WORKER BOSS      12
DAUGHTER             11
MAID                  9
GROUP                 9
WILLIAM               7
OFFICER 2             4
Name: word_count_corrected, dtype: int64

In [86]:
nickel_boys.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
TURNER                  1678
ELWOOD                  1108
HATTIE                   736
PETE                     596
SPENCER                  333
HARPER                   294
MR. BLAKELY              281
MALE TV ANNOUNCER        234
MALE TEACHER             166
MALE TV CHARACTER        152
BOY                      145
MLK                      135
MR. HILL                 121
MAN 3                    119
MALE RADIO ANNOUNCER     103
EVELYN                   101
GRIFF                    100
DENISE                    95
NURSE                     84
DESMOND                   82
MRS. HARDEE               69
PERCY                     67
WOMAN 1                   66
MAN 2                     51
MALE OFFICER              48
LARRY                     44
MALE TEACHER 2            41
JOHN                      37
MIKE                      36
WOMAN 2                   36
MALE CHARACTER 1          32
MAN                       29
MILLIE                    26
MALE STUDENT 3            23
MAN 1                     22
BOY 2                     22
ERICA                     21
BOYS                      20
MALE CHARACTER 2          18
BOY 1                     17
MALE STUDENT              17
DAN                       16
WOMAN                     14
MAN ON TV                 14
MALE ANNOUNCER            13
EARL                      12
COREY                     12
MR. MARCONI               10
EVELYN'S MOM               8
JAIME                      7
BOY 3                      6
ASTRONAUT                  6
MALE STUDENT 1             5
MALE COACH                 3
BOY 5                      2
BOY 4                      2
LONNIE                     2
KIDS                       1
MALE STUDENT 2             1
Name: word_count_corrected, dtype: int64

In [87]:
dune_part_two.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)

speaker
PAUL                   1440
STILGAR                 751
CHANI                   740
JESSICA                 604
IRULAN                  434
GURNEY                  430
MOHIAM                  293
FEYD-RAUTHA             287
BARON HARKONNEN         256
FREMEN WOMAN            231
MARGOT                  182
HARKONNEN MAN           158
FREMEN MAN              153
EMPEROR                 149
MAN                     148
RABBAN                   89
GROUP                    80
SOUTHERN MAN             56
GLADIATOR ANNOUNCER      56
SOUTHERN WOMAN           52
WOMAN                    51
ALIA                     43
JAMIS                    25
PRIESTESS                22
SISTER                   22
HARKONNEN ANNOUNCER      10
LANVILLE                  9
FEDAYKIN FIGHTER          9
REVEREND MOTHER           8
FREMEN WOMEN              8
ALIEN                     7
SLAVE MASTER              7
FEDAYKIN WOMAN            2
PRIESTESS 2               1
Name: word_count_corrected, dtype: int64

In [88]:
the_substance.groupby('speaker')['word_count_corrected'].sum().sort_values(ascending=False)
# MAN appears to be the top speaking character in The Substance, but MAN actually denotes several unnamed men.
# Therefore, Sue speaks the most words.

speaker
MAN                673
SUE                614
ELISABETH          599
HARVEY             568
HOST               216
OLIVER             193
FRED               132
TV MAN 7           102
DIRECTOR            99
NURSE               92
HOOKUP              86
DOCTOR              79
WOMAN               77
TV MAN              51
PAPARAZZI           46
MONSTROELISASUE     34
TV MAN 5            13
GEORGE              13
TV MAN 3             8
CREW MEMBER          8
TV MAN 2             6
TV MAN 4             6
TV MAN 6             6
WAITRESS             5
TV MAN 1             3
PHOTOGRAPHER         1
ISABELLA             1
Name: word_count_corrected, dtype: int64

# Data Analysis for Article Discussion: Directors and gender
Below is some data analysis on who directed each film. We can see in the data that each award year featured just one film directed by a woman: this year, Chloe Zhao's "Hamnet" and last year, Coralie Fargeat's "The Substance."

This data isn't visualized in Flourish but is discussed in the article.

In [89]:
awards_97th.groupby('film')['director_gender'].value_counts()

film                director_gender
A COMPLETE UNKNOWN  MALE                970
ANORA               MALE               2439
CONCLAVE            MALE               1326
DUNE: PART TWO      MALE               1030
EMILIA PEREZ        MALE               1919
I'M STILL HERE      MALE               1925
NICKEL BOYS         MALE                582
THE BRUTALIST       MALE               2532
THE SUBSTANCE       FEMALE              755
WICKED              MALE               2208
Name: count, dtype: int64

In [90]:
awards_98th.groupby('film')['director_gender'].value_counts()

film                      director_gender
BUGONIA                   MALE                754
F-ONE                     MALE               2164
FRANKENSTEIN              MALE                750
HAMNET                    FEMALE             1302
MARTY SUPREME             MALE               3907
ONE BATTLE AFTER ANOTHER  MALE               1376
SENTIMENTAL VALUE         MALE                675
SINNERS                   MALE               1991
THE SECRET AGENT          MALE               2383
TRAIN DREAMS              MALE                850
Name: count, dtype: int64